{% set name = "pyexasol" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d0c6bc29cb669b05d28d9c3e39c773888b1f604e2e233056eda82fba7d215d9

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - numpy >1.26.0,<2
    - pandas >=2.0.0,<3.0.0
    - packaging
    - pyopenssl
    - python-rapidjson
    - rsa
    - websocket-client >=1.0.1

test:
  imports:
    - pyexasol
    - pyexasol.db2
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/badoo/pyexasol
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Exasol python driver with extra features

extra:
  recipe-maintainers:
    - dbast
    - morazow
