{% set name = "pyexasol" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 34ee20702601ef4fca17a6f8b3a317bf2cb25cc8d6dd77440bfac4eaedbdd9fb

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - pandas >=0.22,!=0.23.1
    - pyopenssl >=17.5.0
    - python >=3.6
    - python-rapidjson
    - rsa
    - websocket-client >=0.47.0

test:
  imports:
    - pyexasol
    - pyexasol.db2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/badoo/pyexasol
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Exasol python driver with extra features

extra:
  recipe-maintainers:
    - dbast
    - morazow
