{% set name = "pyexasol" %}
{% set version = "0.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 795490cd810617bf927e0e90b88347facb5e66f58e0e16378fef5d22fadacd60

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - numpy >1.26.0,<2
    - pandas >=2.0.0,<3.0.0
    - packaging
    - pyopenssl
    - python-rapidjson
    - rsa
    - websocket-client >=1.0.1

test:
  imports:
    - pyexasol
    - pyexasol.db2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/badoo/pyexasol
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Exasol python driver with extra features

extra:
  recipe-maintainers:
    - dbast
    - morazow
