schema_version: 1

context:
  name: pyexasol
  version: "2.2.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 6a7c88a8e8760d725157d531d70369967c12141dfc6b63a5d496bdbb775c0c29

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }},<4.0.0
    - websocket-client >=1.0.1,<2
    - packaging >=24.1.0
    - cryptography >=45.0.7
tests:
  - python:
      imports:
        - pyexasol
        - pyexasol.db2
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE.txt
  summary: Exasol python driver with extra features
  homepage: https://github.com/badoo/pyexasol

extra:
  recipe-maintainers:
    - dbast
    - morazow
    - xylar
